version: '1'

services:
  jwt-auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/jwt-auth
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=root123
      - DB_NAME=testdb
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  


